# Generated by Django 4.2.7 on 2025-07-03 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('app_store_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('google_play_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('size_mb', models.FloatField(blank=True, help_text='App size in MB', null=True)),
                ('average_rating', models.FloatField(default=0.0, help_text='Average rating from all sources')),
                ('total_ratings', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list, help_text='JSON list of tags for categorization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata for future extensions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'apps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='apps_name_2a9f76_idx'), models.Index(fields=['category'], name='apps_categor_2a7a1b_idx'), models.Index(fields=['developer'], name='apps_develop_52f43d_idx'), models.Index(fields=['average_rating'], name='apps_average_22bde1_idx'), models.Index(fields=['is_active'], name='apps_is_acti_c86f92_idx')],
            },
        ),
    ]
