# Generated by Django 4.2.7 on 2025-07-03 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('review_notifications', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('reputation_score', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('helpful_review_count', models.IntegerField(default=0)),
                ('preferences', models.JSONField(blank=True, default=dict, help_text='User preferences and settings')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional user metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
