# Generated by Django 4.2.7 on 2025-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conflict', 'Conflict - Admin Review Required')], default='pending', max_length=20),
        ),
    ]
